### PR TITLE
Item branch - make local changes gloabl

### PR DESCRIPTION
**Pull request by ftommasi**
Im making this pull request so that the current item changes can be implemented over the network. I will work on bug fixes and enhancements (i.e. deleting objects once they collide)

### CODE REVIEW

**Comment by ftrelz** [comment]
How's the attack function actually work? All it does is just actually draw the item right?

**Comment by ftommasi** [comment]
The attack function is currently not fully implemented but if you look at InputListener that should give you an idea of what the target is. In short its creating an item for some time and then deleting it.

**Comment by boon2537** [comment]
I will look into matter.js to set up a nice way to do OnCollision callbacks and raycasts later. I think this should be good enough for Friday.

**Comment by ftrelz** [comment]
I like the *.swp lol we need to merge player and character as well. This looks good to me.

**Pull request merged**
